### ISSUE TITLE
Code is hard to understand 

### ISSUE THREAD

**Issue by HypePickups** [zweed4u/new_supr3m31059#10]
Hey man looks like you've got something great here. Im having a bit of trouble reading it and understanding how it works, do you think you could maybe come up with a youtube video tutorial? Im sure you could stretch it out a couple parts and get a good amount of views for it. Also there is no explanation how to use it or anything. I am very confused on how it works or how I would even use it, otherwise great work man.

**Comment by ghost** [comment]
It’s not the developers job to teach you how to learn code.

**Comment by HypePickups** [comment]
rip.. also how did he get it to run on the iphone

**Comment by zweed4u** [comment]
@HypePickups, @copcopcopcop hit the nail on the head. I do not have any intentions of constructing a youtube tutorial to get you up and running. However I do believe it is good practice to include documentation which I have failed to do. I will get around to authoring a README when I have time.
In the meantime you can contact me directly with any questions/ideas you have which may be included in the documentation.

**Comment by HypePickups** [comment]
OK thanks anyways, im just looking of ways to create an app that does the automation (trying to figure out how to get selenium to open safari and run the scripts on it).

**Comment by kinglabrador23** [comment]
might catch that adsense

**Comment by zweed4u** [comment]
Recent commit https://github.com/zweed4u/Supreme/commit/8072640944c9928718472337797cc30fe74822ea should briefly explain on how to setup
