### ISSUE TITLE
'Reponse Empty!'

### ISSUE THREAD

**Issue by kinglabrador23** [zweed4u/new_supr3m31059#11]
It can find the item fine but when it adding it to cart it fails.

'Response Empty! - Problem Adding to Cart! [[ item ]] FAILED!'

**Comment by zweed4u** [comment]
Please provide me with a snippet of your config and other useful traceback information.
Thank you!

**Comment by kinglabrador23** [comment]
Here ya go :) 
This is with the config/cli version python3, not the gui.

I'm guessing theres a problem with the line 256 ?

`[timeComponents]
poll = 3
ghostCheckoutPrevention = 5

[productName] #adjust/add more items here - just be sure to have the same number of products in each section(name, size, color, qty)
name1 = Crewneck 


[productColor]
#String eg. 'Red'
color1 = black 

[productSize]
#String eg. 'Medium', 'OS', 'N/A'
size1 = Medium 

[productQty]
amount1 = 1
`

**Comment by zweed4u** [comment]
I was unable to reproduce.
[Screencast](https://imgur.com/a/EYXvmjY)

**Comment by zweed4u** [comment]
Check for whitespace in your config and make sure to run `supreme_3.py`
Other than that I can't help much as I don't have a traceback unless you provide one.
Try debugging with `print()` to see each response. Also try to replicate functionality manually.

**Comment by kinglabrador23** [comment]
:) Figured it out, my chromedriver was out of date thus the api didn't work.

Thanks for your help mate! I'll be sure to tip after the next drop

**Comment by zweed4u** [comment]
That's awesome man. 
Sorry for the confusion. There's another issue open regarding documentation. https://github.com/zweed4u/Supreme/issues/10
I plan to outline and make execution more user friendly.
I hope it works for you in future releases. No need for a tip. :+1:

**Comment by nediazc** [comment]
Hi

I'm having an issue adding the items to the cart.
the item is found but the cart shows empty.

```
[[ Thread-1]] Striped :: Large :: Black :: 1 :: Thread initialized!
[[ Thread-1 ]] 2018-12-16 18:48:40.612961 EST :: [[[Striped](url) L/S Polo ]] 172029 found ( MATCHING ITEM DETECTED )
[[ Thread-1 ]] 2018-12-16 18:48:40.613071 EST :: Selecting [[Striped L/S Polo]] ( 172029 )
[[ Thread-1 ]] 2018-12-16 18:48:40.737647 EST :: Selecting size for [[ Striped L/S Polo ]] - Large ( Black )  ( 63395 )
[[ Thread-1 ]] 2018-12-16 18:48:40.737743 EST :: Adding [[ Striped L/S Polo ]] to cart...
https://www.supremenewyork.com/mobile/
[[ Thread-1 ]] 2018-12-16 18:48:41.010923 EST :: [[ Striped L/S Polo - Black - Large ]] added to cart!
	EditThisCookie Import	
####################################################################################################################################
[]
####################################################################################################################################
Couldn't find order billing name field
```
