### ISSUE TITLE
Find with product name and special character

### ISSUE THREAD

**Issue by ScratLpp** [zweed4u/new_supr3m31059#14]
Hi zweed4u,

When supreme sell a new product with an other brand for example Jan Paul Gaulthier, in the product name we have special character. (®)

And the bot doesn't find the product :
[Image](http://prntscr.com/nahddp)

But when i set only "tee" the bot found the product name : 
[Image](http://prntscr.com/nahrr8)

I can't just set "tee" because we have many product with this keyword and the bot can't run properly. What can i modify on supreme.py for accept to find this character ?

Thank's
ScratLpp

**Comment by zweed4u** [comment]
What does the `productName` section of your config look like in the first instance? Are you using ascii?
It's somewhat expected that the user will be smart about selecting keywords for matches.

![ezgif-5-148f89b1b4d5](https://user-images.githubusercontent.com/2364057/55971548-b2982d00-5c4f-11e9-8138-91bdcdcb64bf.gif)

**Comment by ScratLpp** [comment]
> It's somewhat expected that the user will be smart about selecting keywords for matches.

Yes of course, it's why i would set all the title product :)

[My notepad++ is configure on UTF-8](http://prntscr.com/nanedi)
I convert on ANSI and the search work properly with the character 👍 

Thank you maestro !

**Comment by ScratLpp** [comment]
> It's somewhat expected that the user will be smart about selecting keywords for matches.
Yes of course, it's why i would set all the title product :)

[My notepad++ is configure on UTF-8](http://prntscr.com/nanedi)

I convert on ANSI and the search work properly with th character 👍 
Thank you mastro !
