### ISSUE TITLE
Recaptcha

### ISSUE THREAD

**Issue by ScratLpp** [zweed4u/new_supr3m31059#15]
Hello zweed4u,

I have a simply question to how the bot buy without recaptcha because when i myself click on the button "Pocess payment" a recaptcha appear.

When the bot run, the recaptcha doesn't appear, so for my next thursday try i would like to know if the bot can buy without or if the bot close the google chrome window without buy the product ?

Thank's for advance,
ScratLpp

**Comment by ScratLpp** [comment]
If it not the case, can we imagine import cookie or google auto login on headless chrome with selenium ?

**Comment by ScratLpp** [comment]
After many and many research i found this article, that tell us how bypass recaptcha. Maybe it's useful for you maybe not. I hope it's can be help you

[https://kb.apify.com/overcoming-anti-scraping-protection/several-tips-how-to-bypass-website-anti-scraping-protections](https://kb.apify.com/overcoming-anti-scraping-protection/several-tips-how-to-bypass-website-anti-scraping-protections)

**Comment by zweed4u** [comment]
Interesting although not super pertinent.
I recommend you look into token harvesting as well as checking out some tricks you can do with cookies, etc. that is involved in canvas fingerprinting.
Unfortunately I don't have any intentions of expanding on/supporting this.
