### ISSUE TITLE
ATC payload missing style

### ISSUE THREAD

**Issue by superyl** [zweed4u/new_supr3m31059#2]
i.e. 
addPayload={
    'size': str(variant),
    'qty':  '1'
    'style': 'Red'
}

**Comment by zweed4u** [comment]
Should be resolved in latest commits. :+1: 
[ef26d90dbe1f127972866a7f86036dcffd417e51](https://github.com/zweed4u/Supreme/commit/ef26d90dbe1f127972866a7f86036dcffd417e51)
[a5f11d66d62971c14a6d076509e9387f916f6292](https://github.com/zweed4u/Supreme/commit/a5f11d66d62971c14a6d076509e9387f916f6292)

Update:
Threading commit: 
[9f53aef3905a335169e17937f0eb3601f64bda6c](https://github.com/zweed4u/Supreme/commit/9f53aef3905a335169e17937f0eb3601f64bda6c)
