### ISSUE TITLE
ConfigParser.NoSelectionError: No section : 'timeCompents'

### ISSUE THREAD

**Issue by ghost** [zweed4u/new_supr3m31059#5]
ConfigParser.NoSelectionError: No section : 'timeComponents'

**Comment by zweed4u** [comment]
You may have mistakenly deleted that section in your config.
Make sure you only change the values in the example without removing any sections.

**Comment by ghost** [comment]
I left it as it was it does contain timeComponents.

**Comment by zweed4u** [comment]
You should have copied the file config.cfg.example to a renamed config.cfg file with all of your desired values. If this hasn't been completed make sure to do so. 
Reading the error, it look like you must have touched the script then. Check lines 21 and 22 in the python file.
Its unclear whether its a typo/user issue regarding the title and comments.
My recommendation is to go through the script and make sure that each section referenced is in your config.

**Comment by zweed4u** [comment]
Thinking of what else your issue could be, obviously make sure to invoke from within the scripts and config directory.
