### ISSUE TITLE
CheckoutResp State 'dup' ?

### ISSUE THREAD

**Issue by XinyuYe** [zweed4u/new_supr3m31059#7]
I can't checkout and every time state of checkoutResp.json() is 'dup' in the end.

**Comment by zweed4u** [comment]
Haven't used/worked on this in a while. 
Just snooped a bit. Pull [latest](https://github.com/zweed4u/Supreme/commit/9f700d3254b1c18e8695d5d53f8eca343cbae012) and check results.
It would be helpful to post outputs of various responses to ensure that the checkout process is progressing as expected.

New since development:
- `asec` key in Desktop checkout data
- `/pooky` endpoint
- Minor key renames/revisions

[Mobile (iOS) checkout form](https://pastebin.com/XTRCxQgQ) 
[Desktop checkout form](https://pastebin.com/jtLsYnjv)

**Comment by XinyuYe** [comment]
Use tagless to test,

[[Thread-1]] 2017-12-06 19:58:57.600918 EST :: Adding [[Supreme®/Hanes® Tagless Tees (3 Pack)]] to cart...
[[Thread-1]] 2017-12-06 19:58:57.665331 EST :: [[Supreme®/Hanes® Tagless Tees (3 Pack) - White - Medium]] added to cart!
[[Thread-1]] Waiting for 3 seconds to avoid ghost checkout!
[[Thread-1]] Waiting for 2 seconds to avoid ghost checkout!
[[Thread-1]] Waiting for 1 seconds to avoid ghost checkout!
[[Thread-1]] 2017-12-06 19:59:00.678309 EST :: Firing checkout request for [[Supreme®/Hanes® Tagless Tees (3 Pack)]]
[[Thread-1]] 2017-12-06 19:59:00.834080 EST :: Checkout for [[Supreme®/Hanes® Tagless Tees (3 Pack)]] dup

or if I print checkoutResp.json():
[[Thread-2]] 2017-12-06 20:04:49.849121 EST :: Checkout for [[Supreme®/Hanes® Tagless Tees (3 Pack)]] {u'status': u'dup'}

**Comment by zweed4u** [comment]
Interesting. I just tried with some dummy information in my config and got this expected response:
`{u'order': {}, u'credit_card': {u'number': [u'is not a valid credit card number']}}`
Are you using your actual information? If you change values in your config does the response change?

**Comment by XinyuYe** [comment]
Yes, I am using valid credit card and address information to test, if I use the default information, I will also get the same response as you

**Comment by Textcat** [comment]
Do you have any idea about how to handle the `/pooky` endpoint? The request payload is messy characters in my Chrome and Firefox inspector.

**Comment by zweed4u** [comment]
@XinyuYe @luiyezheng I haven't been able to revisit this. @luiyezheng Unfortunately, since the data is an octet-stream I believe the best practice would be to transfer cookies to a webdriver and complete execution with user intervention, unless we figure out encoding/attachment.

**Comment by zweed4u** [comment]
@XinyuYe @luiyezheng 
Regarding [15c2ce50b6d32a63e2d57e7226d86bdd92ac4416](https://github.com/zweed4u/Supreme/commit/15c2ce50b6d32a63e2d57e7226d86bdd92ac4416):
I finally got around to integrating the web driver - it works but has dead code, not cleaned whatsoever, and has each thread paused after transferring session. I also included a cookie print out that you can import using EditThisCookie extension. I'll make use of sending keys when I get around to it. I believe they've been known to change selectors so I'm lowering the priority on automation in the web driver session.

**Comment by SebastianBoehler** [comment]
> I can't checkout and every time state of checkoutResp.json() is 'dup' in the end.
dup means you've already ordered this item.

https://d17ol771963kd3.cloudfront.net/assets/application-ee792bf5c0fc93a453430e43609796c7.js
