### ISSUE TITLE
Cannot find some elements in checkout

### ISSUE THREAD

**Issue by luquitared** [zweed4u/new_supr3m31059#9]
I have used and tinkered with this repository before but I have not seen this issue. When going into the checkout, selenium cannot find many of the inputs to fill out the checkout page. Here is the output:

Couldn't find order billing name field
Click to continue automation...
Couldn't find order email field
Click to continue automation...
Couldn't find bo field (address)
Click to continue automation...
Couldn't find order billing zip field
Click to continue automation...
Couldn't find order billing country drowpdown/value
Click to continue automation...
Couldn't find credit card month dropdown/value
Click to continue automation...
Couldn't find credit card year dropdown/value
Click to continue automation...
Couldn't find orcer field (card cvv)
Click to continue automation...
NEXT STEP IS TO CHECKOUT

When I click to continue the automation, it continues to not find a lot of the elements. It does however find the telephone ID and the credit card ID and fills them out. It is odd because in the code the billing address for example is grabbed the same exact way as the telephone...
`customer_name = webdriver_instance.find_element_by_id("order_billing_name")
customer_telephone = webdriver_instance.find_element_by_id('order_tel')`

It also does not appear to me that Supreme has changed any HTML of theirs...
Any ideas? Thanks, and zweed4u if you read this thank you for this awesome piece of software!!!

**Comment by zweed4u** [comment]
Pushed a [change](https://github.com/zweed4u/Supreme/commit/dbbb6a78e25f356cb2db7c6737e8b4da238d38c0) @luquitared 
Let me know if it works for you

**Comment by luquitared** [comment]
Fixed! Thanks so much!!! You are the man!

**Comment by luquitared** [comment]
Hi zweed4u,
Don't mean to bother you bro... But again the same issue is occurring. Do you know a fix?

**Comment by zweed4u** [comment]
@luquitared Just got to look at it. Retrieving elements from the DOM via name and id return Proxy objects. They're playing games. Thinking of implementing a search for parent element (ie. 'input string required order_billing_name') then parse for children as a workaround for now but definitely not a viable long term solution.

**Comment by zweed4u** [comment]
@luquitared Just pushed a [commit](https://github.com/zweed4u/Supreme/commit/df96197784cb9e65670d8a258288acc53cc1fc5b) to address the returned proxy objects. Instead of scary selectors/xpaths I went with javascript execution, I'm unsure if it will raise flags upon release but give it a spin and let me know if it works for you,

**Comment by luquitared** [comment]
Wow thank you so much! I will definitely test it out and let you know.

**Comment by luquitared** [comment]
Just tested it today, works great
